joint_limits:
  HeadPitch:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: false
    max_acceleration: 0
  HeadRoll:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  LAnklePitch:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 0
  LAnkleRoll:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 0
  LElbowRoll:
    has_velocity_limits: true
    max_velocity: 3.7
    has_acceleration_limits: false
    max_acceleration: 0
  LElbowYaw:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  LHand:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LHipPitch:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  LHipRoll:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  LKneePitch:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulderPitch:
    has_velocity_limits: true
    max_velocity: 2.2
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulderYaw:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  LWristPitch:
    has_velocity_limits: true
    max_velocity: 3.75
    has_acceleration_limits: false
    max_acceleration: 0
  LWristRoll:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: false
    max_acceleration: 0
  LWristYaw:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: false
    max_acceleration: 0
  NeckPitch:
    has_velocity_limits: true
    max_velocity: 2.2
    has_acceleration_limits: false
    max_acceleration: 0
  NeckYaw:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  RAnklePitch:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 0
  RAnkleRoll:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 0
  RElbowRoll:
    has_velocity_limits: true
    max_velocity: 3.7
    has_acceleration_limits: false
    max_acceleration: 0
  RElbowYaw:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  RHand:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RHipPitch:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  RHipRoll:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  RKneePitch:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulderPitch:
    has_velocity_limits: true
    max_velocity: 2.2
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulderYaw:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  RWristPitch:
    has_velocity_limits: true
    max_velocity: 3.75
    has_acceleration_limits: false
    max_acceleration: 0
  RWristRoll:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: false
    max_acceleration: 0
  RWristYaw:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: false
    max_acceleration: 0
  TrunkYaw:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0